// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void kmanim1_Animation(lv_obj_t * TargetObject, int delay);
void kmanim2_Animation(lv_obj_t * TargetObject, int delay);
void mvanim_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Chart1_Xaxis;
extern lv_obj_t * ui_Chart1_Yaxis1;
extern lv_obj_t * ui_Chart1_Yaxis2;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_dc1_png);    // assets/dc1.png
LV_IMG_DECLARE(ui_img_dc2_png);    // assets/dc2.png
LV_IMG_DECLARE(ui_img_dc3_png);    // assets/dc3.png
LV_IMG_DECLARE(ui_img_mv1_png);    // assets/mv1.png
LV_IMG_DECLARE(ui_img_mv2_png);    // assets/mv2.png
LV_IMG_DECLARE(ui_img_kw1_png);    // assets/kw1.png
LV_IMG_DECLARE(ui_img_km2_png);    // assets/km2.png
LV_IMG_DECLARE(ui_img_km3_png);    // assets/km3.png
LV_IMG_DECLARE(ui_img_km4_png);    // assets/km4.png
LV_IMG_DECLARE(ui_img_kuan1_png);    // assets/kuan1.png
LV_IMG_DECLARE(ui_img_kuan2_png);    // assets/kuan2.png



LV_FONT_DECLARE(ui_font_Be20);
LV_FONT_DECLARE(ui_font_Be30);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
